version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_chatbot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - chatbot_network

  spring-boot-app:
    image: imdat1/sql_chatbot
    container_name: sql_chatbot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      FLASK_URL: http://flask-app:5000/ask
      FLASK_URL2: http://flask-app:5000/connect
      HUGGING_FACE_TOKEN: your_hugging_face_token_here
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - chatbot_network

  flask-app:
    image: imdat1/flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - chatbot_network

  northwind:
    image: bradymholt/postgres-northwind:latest
    ports:
      - "5434:5432"
    networks:
      - chatbot_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chatbot_network

networks:
  chatbot_network:
    name: chatbot_network
    driver: bridge
